### ISSUE TITLE
eslint忽略文件是否必须？

### ISSUE THREAD

**Issue by xubillde** [twfe/clij#1]
.eslintignore 文件
```
build/*.js
src/assets
src/utils
public
dist
```
一键生成常见忽略文件夹是否必须？

**Comment by phodal** [comment]
取决于你的需求了，不过 `src/` 这个如果要 ignore 的话，那说明编译脚本不对啊，源码才放 src 里。

**Comment by xubillde** [comment]
是的，src不应该忽略。utils下可能有些js没有遵守，导致无法提交。正常应该都遵守的。嗯嗯

**Comment by xubillde** [comment]
测试了，兼容性有点问题
每个人可能需要自己改下
"husky": "^3.0.0"
nvm安装的node找不到，然后升级到最新版了，就没触发。
后来来回删hook、安装husky和把husky配置移到单独的文件，才生效了。

根目录创建.huskyrc 文件
export PATH="/Users/xubill/.nvm/versions/node/v10.13.0/bin:$PATH"
